stages:
  data_generation:
    cmd: python src/utils/preprocess.py --config=params.yaml
    deps:
    - data/raw/

  train_and_evaluate:
    cmd: python src/train_model.py --config=params.yaml
    deps:
    - - params.yaml
    - src/train_model.py
    - src/utils/preprocess.py  # Fixed typo in the dependency name
    - src/utils/getconfig.py
    - src/utils/keras_cbs.py

  evaluate:
    cmd: python src/model_eval.py --config=params.yaml
    deps:
    - params.yaml
    - src/model_eval.py
    - src/utils/getconfig.py
    - src/utils/preprocess.py

